apiVersion: v1
kind: Service
metadata:
 name: reward-program-dev

spec:
 # This defines which pods are going to be represented by this Service
 # The service becomes a network endpoint for either other services or 
 # maybe external users to connect to (eg browser)
 selector:
  app: reward-program-api
  release: "1.0.4"
 ports:
  - name: http
    port: 8089
    # K8s by default only enable port greater than 30000
    #nodePort: 30080

# ClusterIP makes service only accessble inside k8s cluster
# NodePort expose you service outside the k8s cluster
 type: ClusterIP